[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/booking"
  to = "/pages/booking.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/pages/thank-you.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
